version: '2' # Specifies the version of the Docker Compose file format. This is version 2.

services: # Defines the services that make up your app in this docker-compose file.

  broker: # The name of the first service.
    image: confluentinc/cp-kafka:7.5.1 # The Docker image to use for this service.
    hostname: broker # The hostname for this service.
    container_name: broker # The name of the Docker container.
    ports: # Specifies the ports that are exposed by this service.
      - "9092:9092" # Maps port 9092 on the host to port 9092 on the Docker container.
      - "9101:9101" # Maps port 9101 on the host to port 9101 on the Docker container.
    environment: # Specifies the environment variables for this service.
      KAFKA_NODE_ID: 1 # The ID of the Kafka node.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT' # Maps the listener names to security protocols.
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092' # The listeners that the broker will advertise to producers and consumers.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # The replication factor for the offsets topic.
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0 # The delay for the initial rebalance.
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 # The minimum number of in-sync replicas (ISRs) that must be available for the transaction state log.
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 # The replication factor for the transaction state log.
      KAFKA_JMX_PORT: 9101 # The port for Java Management Extensions (JMX).
      KAFKA_JMX_HOSTNAME: localhost # The hostname for JMX.
      KAFKA_PROCESS_ROLES: 'broker,controller' # The roles for this Kafka process.
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093' # The voters for the controller quorum.
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092' # The listeners for this Kafka broker.
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT' # The name of the listener for inter-broker communication.
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER' # The names of the listeners for the controller.
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs' # The directories where the Kafka logs are stored.
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk' # The ID of the cluster. This should be a unique base64 UUID.

  schema-registry: # The name of the second service.
    image: confluentinc/cp-schema-registry:7.5.1 # The Docker image to use for this service.
    hostname: schema-registry # The hostname for this service.
    container_name: schema-registry # The name of the Docker container.
    depends_on: # Specifies the services that this service depends on.
      - broker # This service depends on the 'broker' service.
    ports: # Specifies the ports that are exposed by this service.
      - "8081:8081" # Maps port 8081 on the host to port 8081 on the Docker container.
    environment: # Specifies the environment variables for this service.
      SCHEMA_REGISTRY_HOST_NAME: schema-registry # The hostname for the Schema Registry.
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092' # The bootstrap servers for the Kafka store.
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081 # The listeners for the Schema Registry.

  connect: # The name of the third service.
    image: cnfldemos/cp-server-connect-datagen:0.6.2-7.5.0 # The Docker image to use for this service.
    hostname: connect # The hostname for this service.
    container_name: connect # The name of the Docker container.
    depends_on: # Specifies the services that this service depends on.
      - broker # This service depends on the 'broker' service.
      - schema-registry # This service depends on the 'schema-registry' service.
    ports: # Specifies the ports that are exposed by this service.
      - "8083:8083" # Maps port 8083 on the host to port 8083 on the Docker container.
    environment: # Specifies the environment variables for this service.
      CONNECT_BOOTSTRAP_SERVERS: 'broker:29092' # The bootstrap servers for Kafka Connect.
      CONNECT_REST_ADVERTISED_HOST_NAME: connect # The advertised hostname for the REST interface.
      CONNECT_GROUP_ID: compose-connect-group # The group ID for Kafka Connect.
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs # The topic for storing connector configurations.
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1 # The replication factor for the config storage topic.
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000 # The interval for flushing offsets.
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets # The topic for storing offsets.
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1 # The replication factor for the offset storage topic.
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status # The topic for storing statuses.
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1 # The replication factor for the status storage topic.
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter # The converter for keys.
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter # The converter for values.
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081 # The URL for the Schema Registry.
      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-7.5.1.jar # The classpath for Kafka Connect.
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor" # The interceptor classes for producers.
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor" # The interceptor classes for consumers.
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components" # The path for plugins.
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR # The loggers for Kafka Connect.

  control-center: # The name of the fifth service.
    image: confluentinc/cp-enterprise-control-center:7.5.1 # The Docker image to use for this service.
    hostname: control-center # The hostname for this service.
    container_name: control-center # The name of the Docker container.
    depends_on: # Specifies the services that this service depends on.
      - broker # This service depends on the 'broker' service.
      - schema-registry # This service depends on the 'schema-registry' service.
      - connect # This service depends on the 'connect' service.
      - ksqldb-server # This service depends on the 'ksqldb-server' service.
    ports: # Specifies the ports that are exposed by this service.
      - "9021:9021" # Maps port 9021 on the host to port 9021 on the Docker container.
    environment: # Specifies the environment variables for this service.
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092' # The bootstrap servers for the Control Center.
      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'connect:8083' # The default cluster for Kafka Connect.
      CONTROL_CENTER_CONNECT_HEALTHCHECK_ENDPOINT: '/connectors' # The health check endpoint for Kafka Connect.
      CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ksqldb-server:8088" # The URL for the KSQL DB server.
      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088" # The advertised URL for the KSQL DB server.
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081" # The URL for the Schema Registry.
      CONTROL_CENTER_REPLICATION_FACTOR: 1 # The replication factor for the Control Center.
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1 # The number of partitions for internal topics.
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1 # The number of partitions for the monitoring interceptor topic.
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1 # The replication factor for the Confluent metrics topic.
      PORT: 9021 # The port for this service.

  ksqldb-server: # The name of the sixth service.
    image: confluentinc/cp-ksqldb-server:7.5.1 # The Docker image to use for this service.
    hostname: ksqldb-server # The hostname for this service.
    container_name: ksqldb-server # The name of the Docker container.
    depends_on: # Specifies the services that this service depends on.
      - broker # This service depends on the 'broker' service.
      - connect # This service depends on the 'connect' service.
    ports: # Specifies the ports that are exposed by this service.
      - "8088:8088" # Maps port 8088 on the host to port 8088 on the Docker container.
    environment: # Specifies the environment variables for this service.
      KSQL_CONFIG_DIR: "/etc/ksql" # The directory for KSQL configurations.
      KSQL_BOOTSTRAP_SERVERS: "broker:29092" # The bootstrap servers for KSQL.
      KSQL_HOST_NAME: ksqldb-server # The hostname for KSQL.
      KSQL_LISTENERS: "http://0.0.0.0:8088" # The listeners for KSQL.
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0 # The maximum number of bytes for buffering.
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081" # The URL for the Schema Registry.
      KSQL_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor" # The interceptor classes for producers.
      KSQL_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor" # The interceptor classes for consumers.
      KSQL_KSQL_CONNECT_URL: "http://connect:8083" # The URL for Kafka Connect.
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: 1 # The replication factor for the processing log topic.
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: 'true' # Whether to automatically create the processing log topic.
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: 'true' # Whether to automatically create the processing log stream.

  ksqldb-cli: # The name of the seventh service.
    image: confluentinc/cp-ksqldb-cli:7.5.1 # The Docker image to use for this service.
    container_name: ksqldb-cli # The name of the Docker container.
    depends_on: # Specifies the services that this service depends on.
      - broker # This service depends on the 'broker' service.
      - connect # This service depends on the 'connect' service.
      - ksqldb-server # This service depends on the 'ksqldb-server' service.
    entrypoint: /bin/sh # The entrypoint for this service.
    tty: true # Whether to allocate a pseudo-TTY.

  ksql-datagen: # The name of the eighth service.
    image: confluentinc/ksqldb-examples:7.5.1 # The Docker image to use for this service.
    hostname: ksql-datagen # The hostname for this service.
    container_name: ksql-datagen # The name of the Docker container.
    depends_on: # Specifies the services that this service depends on.
      - ksqldb-server # This service depends on the 'ksqldb-server' service.
      - broker # This service depends on the 'broker' service.
      - schema-registry # This service depends on the 'schema-registry' service.
      - connect # This service depends on the 'connect' service.
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                       cub kafka-ready -b broker:29092 1 40 && \
                       echo Waiting for Confluent Schema Registry to be ready... && \
                       cub sr-ready schema-registry 8081 40 && \
                       echo Waiting a few seconds for topic creation to finish... && \
                       sleep 11 && \
                       tail -f /dev/null'" # The command to run in this service.
    environment: # Specifies the environment variables for this service.
      KSQL_CONFIG_DIR: "/etc/ksql" # The directory for KSQL configurations.
      STREAMS_BOOTSTRAP_SERVERS: broker:29092 # The bootstrap servers for Kafka Streams.
      STREAMS_SCHEMA_REGISTRY_HOST: schema-registry # The host for the Schema Registry.
      STREAMS_SCHEMA_REGISTRY_PORT: 8081 # The port for the Schema Registry.

  rest-proxy: # The name of the ninth service.
    image: confluentinc/cp-kafka-rest:7.5.1 # The Docker image to use for this service.
    depends_on: # Specifies the services that this service depends on.
      - broker # This service depends on the 'broker' service.
      - schema-registry # This service depends on the 'schema-registry' service.
    ports: # Specifies the ports that are exposed by this service.
      - 8082:8082 # Maps port 8082 on the host to port 8082 on the Docker container.
    hostname: rest-proxy # The hostname for this service.
    container_name: rest-proxy # The name of the Docker container.
    environment: # Specifies the environment variables for this service.
      KAFKA_REST_HOST_NAME: rest-proxy # The hostname for the Kafka REST Proxy.
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker:29092' # The bootstrap servers for the Kafka REST Proxy.
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082" # The listeners for the Kafka REST Proxy.
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081' # The URL for the Schema Registry.